name: Lint and check every commit and pull request

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    strategy:
      matrix:
        node-version: [14.17.1, 16.3.0]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: textbook/git-checkout-submodule-action@master
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.2.x
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm check
